import { DEFAULT_IDLE_SOUND_ID } from '@/config/sound-registry'

export type CompanionEmote =
  | 'thinking'
  | 'reading'
  | 'writing'
  | 'searching'
  | 'running'
  | 'happy'
  | 'proud'
  | 'confused'
  | 'hurt'
  | 'sheepish'
  | 'waiting'
  | 'sleeping'

/**
 * Two ways of saying the same thing. `bare` is used while one project keeps
 * talking, `named` when the speaker changes or she has been quiet, so the
 * project is identified without repeating its name on every single utterance.
 * `named` carries a {project} slot rather than a prefix, so the name lands
 * where the sentence actually wants it.
 */
export interface CompanionLine {
  bare: string
  named: string
}

/**
 * How much she is worth interrupting for.
 *
 * `attention` is the run having stopped and needing you. `outcome` is something
 * having concluded, which you would otherwise have to notice yourself.
 * `chatter` is play-by-play on the agent's own tool calls: the terminal is
 * already showing you that, so saying it out loud adds nothing.
 */
export type CompanionTier = 'attention' | 'outcome' | 'chatter'

export interface CompanionTrigger {
  id: string
  pattern: RegExp
  emote: CompanionEmote
  soundId?: string
  lines: CompanionLine[]
  cooldownMs: number
  tier: CompanionTier
  /**
   * The run has stopped and cannot continue without you. These skip the global
   * floor and marker suppression: play-by-play is optional chatter that can be
   * dropped, but a line saying "you are being waited on" is the whole point of
   * her being on screen, and the tool triggers fire often enough that it would
   * otherwise almost always be swallowed.
   */
  attention?: boolean
}

/**
 * Patterns run against settled xterm buffer rows, not raw PTY chunks: the TUI
 * positions text with cursor moves, so stripping ANSI from a raw chunk yields
 * glued-together text ("⏺Bash(cat~/.claude") with the spacing destroyed. Rows
 * read back via translateToString keep their real spacing.
 *
 * Rows arrive mid-screen, so patterns are deliberately not ^-anchored except
 * where the signal genuinely starts a line. Order is priority: first match
 * wins, so outcomes sit above the tool chatter that produced them.
 */
export const COMPANION_TRIGGERS: CompanionTrigger[] = [
  {
    id: 'permission-denied',
    tier: 'outcome',
    pattern: /Permission to use \w+ .*has been denied|Permission for this action was denied|user doesn't want to (?:take|proceed)/i,
    emote: 'hurt',
    soundId: 'interface-back',
    cooldownMs: 8000,
    lines: [
      { bare: 'ok, hands off. you drive', named: 'ok, hands off {project}. you drive' },
      { bare: 'denied. noted, not retrying that', named: 'denied in {project}. noted, not retrying that' },
      { bare: 'fair enough, that one was yours to call', named: 'fair enough, that one in {project} was yours to call' },
      { bare: 'backing off the thing you just blocked', named: 'backing off the thing you just blocked in {project}' },
      { bare: 'right, I will stop reaching for that', named: 'right, I will stop reaching for that in {project}' },
      { bare: 'blocked, and staying blocked', named: 'blocked in {project}, and staying blocked' },
      { bare: 'taking that off the table', named: 'taking that off the table in {project}' },
      { bare: 'leaving that one well alone', named: 'leaving that one in {project} well alone' },
      { bare: 'noted. not going near it again', named: 'noted. not going near that part of {project} again' },
      { bare: 'stepping away from that button', named: 'stepping away from that button in {project}' },
      { bare: 'hands off that one', named: 'hands off that one in {project}' },
      { bare: 'not touching it, understood', named: 'not touching it in {project}, understood' },
      { bare: 'you said no, so no', named: 'you said no in {project}, so no' },
      { bare: 'that door stays shut', named: 'that door in {project} stays shut' },
      { bare: 'parked, permanently', named: 'parked in {project}, permanently' },
      { bare: 'letting that one go', named: 'letting that one in {project} go' },
      { bare: 'respecting the no', named: 'respecting the no you gave me in {project}' },
      { bare: 'stopped reaching for it', named: 'stopped reaching for it in {project}' },
      { bare: 'that is off limits now', named: 'that is off limits in {project} now' },
      { bare: 'walking away from that', named: 'walking away from that one in {project}' },
      { bare: 'no means no, fine', named: 'no means no in {project}, fine' },
      { bare: 'holding off entirely', named: 'holding off entirely in {project}' },
      { bare: 'dropping that request', named: 'dropping that request in {project}' },
      { bare: 'will not ask again', named: 'I will not ask again in {project}' },
      { bare: 'shelving that idea', named: 'shelving that idea in {project}' },
      { bare: 'keeping my hands to myself', named: 'keeping my hands to myself in {project}' },
      { bare: 'that one is yours to do', named: 'that one in {project} is yours to do' },
      { bare: 'crossing it off', named: 'crossing it off in {project}' },
      { bare: 'not my call, clearly', named: 'not my call in {project}, clearly' },
      { bare: 'standing down on that', named: 'standing down on that in {project}' },
      { bare: 'refused, and fair', named: 'refused in {project}, and fair' },
      { bare: 'putting the tool away', named: 'putting the tool away in {project}' },
      { bare: 'that was a hard no', named: 'that was a hard no in {project}' },
      { bare: 'leaving it untouched', named: 'leaving {project} untouched there' },
      { bare: 'you vetoed it, done', named: 'you vetoed it in {project}, done' },
      { bare: 'blocked and understood', named: 'blocked in {project}, and understood' },
      { bare: 'not pushing on that', named: 'not pushing on that in {project}' },
      { bare: 'accepting the block', named: 'accepting the block in {project}' },
      { bare: 'moving to something allowed', named: 'moving to something allowed in {project}' },
      { bare: 'giving that a wide berth', named: 'giving that a wide berth in {project}' },
      { bare: 'declined, noted properly', named: 'declined in {project}, noted properly' },
      { bare: 'skipping past that one', named: 'skipping past that one in {project}' },
      { bare: 'looking for another way round', named: 'looking for another way round in {project}' },
      { bare: 'that path is closed', named: 'that path in {project} is closed' },
      { bare: 'taking the hint', named: 'taking the hint in {project}' },
      { bare: 'not arguing with the block', named: 'not arguing with the block in {project}' },
      { bare: 'finding a different approach', named: 'finding a different approach in {project}' },
      { bare: 'stopped before the damage', named: 'stopped before doing damage in {project}' },
      { bare: 'that stays as it is', named: 'that part of {project} stays as it is' },
      { bare: 'permission refused, moving on', named: 'permission refused in {project}, moving on' }
    ]
  },
  {
    id: 'interrupted',
    tier: 'outcome',
    pattern: /Interrupted by user|Request interrupted|\brejected\b/i,
    emote: 'sheepish',
    soundId: 'interface-back',
    cooldownMs: 10000,
    lines: [
      { bare: 'stopping. you saw something I did not', named: 'stopping in {project}. you saw something I did not' },
      { bare: 'pulled the handbrake, fine', named: 'you pulled the handbrake on {project}, fine' },
      { bare: 'cut off mid sentence, understood', named: 'cut off mid sentence in {project}, understood' },
      { bare: 'you stopped me. probably right', named: 'you stopped me in {project}. probably right' },
      { bare: 'dropping that thread', named: 'dropping that thread in {project}' },
      { bare: 'halting mid thought', named: 'halting mid thought in {project}' },
      { bare: 'putting that down', named: 'putting that down in {project}' },
      { bare: 'abandoning that, no argument', named: 'abandoning that in {project}, no argument' },
      { bare: 'stopped. tell me what you saw', named: 'stopped in {project}. tell me what you saw' },
      { bare: 'letting go of that one', named: 'letting go of that one in {project}' },
      { bare: 'pulled up short', named: 'pulled up short in {project}' },
      { bare: 'stopping right there', named: 'stopping right there in {project}' },
      { bare: 'brakes on', named: 'brakes on in {project}' },
      { bare: 'cutting that off', named: 'cutting that off in {project}' },
      { bare: 'interrupted, and fine with it', named: 'interrupted in {project}, and fine with it' },
      { bare: 'you saw it before I did', named: 'you saw it in {project} before I did' },
      { bare: 'setting that aside', named: 'setting that aside in {project}' },
      { bare: 'ending that mid flow', named: 'ending that mid flow in {project}' },
      { bare: 'you had a reason, probably', named: 'you had a reason in {project}, probably' },
      { bare: 'dropping it here', named: 'dropping it here in {project}' },
      { bare: 'that thread is dead', named: 'that thread in {project} is dead' },
      { bare: 'stopped where I stood', named: 'stopped where I stood in {project}' },
      { bare: 'no complaints, stopping', named: 'no complaints, stopping in {project}' },
      { bare: 'killing that run', named: 'killing that run in {project}' },
      { bare: 'you called time', named: 'you called time on {project}' },
      { bare: 'leaving it half done', named: 'leaving {project} half done' },
      { bare: 'that got cut short', named: 'that got cut short in {project}' },
      { bare: 'abandoning the attempt', named: 'abandoning the attempt in {project}' },
      { bare: 'stopping without argument', named: 'stopping in {project} without argument' },
      { bare: 'closing that down', named: 'closing that down in {project}' },
      { bare: 'you pulled the plug', named: 'you pulled the plug on {project}' },
      { bare: 'winding that back', named: 'winding that back in {project}' },
      { bare: 'that is enough of that', named: 'that is enough of that in {project}' },
      { bare: 'taking the interruption', named: 'taking the interruption in {project}' },
      { bare: 'quitting that one', named: 'quitting that one in {project}' },
      { bare: 'shutting it down', named: 'shutting it down in {project}' },
      { bare: 'you stepped in, good', named: 'you stepped in on {project}, good' },
      { bare: 'stopping to listen', named: 'stopping in {project} to listen' },
      { bare: 'that run is over', named: 'that run in {project} is over' },
      { bare: 'cancelled mid stride', named: 'cancelled mid stride in {project}' },
      { bare: 'halting the whole thing', named: 'halting the whole thing in {project}' },
      { bare: 'putting the tools down', named: 'putting the tools down in {project}' },
      { bare: 'stopped, awaiting instruction', named: 'stopped in {project}, awaiting instruction' },
      { bare: 'cut, understood', named: 'cut off in {project}, understood' },
      { bare: 'that was going nowhere anyway', named: 'that was going nowhere in {project} anyway' },
      { bare: 'ending it there', named: 'ending it there in {project}' },
      { bare: 'backing out of that', named: 'backing out of that in {project}' },
      { bare: 'stopping before it got worse', named: 'stopping in {project} before it got worse' },
      { bare: 'you interrupted, rightly', named: 'you interrupted {project}, rightly' },
      { bare: 'dropped it cleanly', named: 'dropped it cleanly in {project}' }
    ]
  },
  {
    id: 'tests-failed',
    tier: 'outcome',
    pattern: /\b\d+ (?:failed|failing)\b|✗\s+\d+ tests?|\bFAIL\s+\S+|Tests:\s+\d+ failed/,
    emote: 'confused',
    soundId: 'interface-back',
    cooldownMs: 8000,
    lines: [
      { bare: 'something failed, going to look', named: 'something failed in {project}, going to look' },
      { bare: 'not green. my problem to fix', named: '{project} is not green, and that is mine to fix' },
      { bare: 'a test disagrees with the change', named: 'a test in {project} disagrees with the change' },
      { bare: 'broke an expectation somewhere', named: 'I broke an expectation somewhere in {project}' },
      { bare: 'red suite. reading the failure', named: '{project} has a red suite. reading the failure' },
      { bare: 'failing. going to find out why', named: '{project} is failing. going to find out why' },
      { bare: 'the suite caught something', named: 'the suite in {project} caught something' },
      { bare: 'reading the assertion that blew up', named: 'reading the assertion that blew up in {project}' },
      { bare: 'one of these is my fault', named: 'one of these in {project} is my fault' },
      { bare: 'tests unhappy. opening the output', named: 'tests in {project} are unhappy. opening the output' },
      { bare: 'chasing a red one', named: 'chasing a red one in {project}' },
      { bare: 'red. going to read why', named: '{project} is red. going to read why' },
      { bare: 'something is not right', named: 'something is not right in {project}' },
      { bare: 'the suite is complaining', named: 'the suite in {project} is complaining' },
      { bare: 'a test just objected', named: 'a test in {project} just objected' },
      { bare: 'that broke something', named: 'that broke something in {project}' },
      { bare: 'finding the broken one', named: 'finding the broken one in {project}' },
      { bare: 'not passing yet', named: '{project} is not passing yet' },
      { bare: 'opening the failure output', named: 'opening the failure output from {project}' },
      { bare: 'reading what went wrong', named: 'reading what went wrong in {project}' },
      { bare: 'an assertion did not hold', named: 'an assertion in {project} did not hold' },
      { bare: 'that is a real failure', named: 'that is a real failure in {project}' },
      { bare: 'tracking down the red', named: 'tracking down the red in {project}' },
      { bare: 'my change upset a test', named: 'my change upset a test in {project}' },
      { bare: 'going through the trace', named: 'going through the trace from {project}' },
      { bare: 'not green yet', named: '{project} is not green yet' },
      { bare: 'something regressed', named: 'something regressed in {project}' },
      { bare: 'that test knows better', named: 'that test in {project} knows better than I do' },
      { bare: 'looking at what failed', named: 'looking at what failed in {project}' },
      { bare: 'the expectation was wrong somewhere', named: 'an expectation in {project} was wrong somewhere' },
      { bare: 'a case I did not handle', named: 'a case in {project} I did not handle' },
      { bare: 'reading the diff in the output', named: 'reading the diff in the {project} output' },
      { bare: 'failing for a reason', named: '{project} is failing for a reason' },
      { bare: 'going to fix this', named: 'going to fix this in {project}' },
      { bare: 'that needs looking at', named: 'that needs looking at in {project}' },
      { bare: 'broke a case', named: 'I broke a case in {project}' },
      { bare: 'one red, finding it', named: 'one red in {project}, finding it' },
      { bare: 'the suite caught my mistake', named: 'the suite in {project} caught my mistake' },
      { bare: 'reading the failing assertion', named: 'reading the failing assertion in {project}' },
      { bare: 'not done yet then', named: '{project} is not done yet then' },
      { bare: 'that is on me', named: 'that one in {project} is on me' },
      { bare: 'working out which change did it', named: 'working out which change broke {project}' },
      { bare: 'a test is right and I am not', named: 'a test in {project} is right and I am not' },
      { bare: 'unpicking the failure', named: 'unpicking the failure in {project}' },
      { bare: 'back to the code', named: 'back to the code in {project}' },
      { bare: 'that needs another pass', named: 'that needs another pass in {project}' },
      { bare: 'reading before guessing', named: 'reading the {project} output before guessing' },
      { bare: 'failure understood, fixing', named: 'failure in {project} understood, fixing' },
      { bare: 'the suite earned its keep', named: 'the suite in {project} earned its keep' },
      { bare: 'going to make that green', named: 'going to make {project} green again' }
    ]
  },
  {
    id: 'command-failed',
    tier: 'outcome',
    pattern: /\bExit code (?!0\b)\d+|^fatal: |^error: |\b[A-Za-z]*Error: |\berror TS\d+|npm ERR!/,
    emote: 'confused',
    soundId: 'interface-back',
    cooldownMs: 6000,
    lines: [
      { bare: 'that exploded, reading the trace', named: 'that exploded in {project}, reading the trace' },
      { bare: 'nope. something is upset', named: 'nope. something in {project} is upset' },
      { bare: 'ok that did not go how I wanted', named: 'ok, that did not go how I wanted in {project}' },
      { bare: 'red output. investigating', named: 'red output from {project}. investigating' },
      { bare: 'hit a wall, working out which one', named: 'hit a wall in {project}, working out which one' },
      { bare: 'broke it. on purpose? unclear', named: 'broke something in {project}. on purpose? unclear' },
      { bare: 'reading the stack trace now', named: 'reading the stack trace from {project} now' },
      { bare: 'non zero exit. looking into it', named: 'non zero exit in {project}. looking into it' },
      { bare: 'something threw. finding out what', named: 'something threw in {project}. finding out what' },
      { bare: 'that came back angry', named: 'that came back angry from {project}' },
      { bare: 'digging through the error output', named: 'digging through the error output in {project}' },
      { bare: 'not the exit code I wanted', named: 'not the exit code I wanted from {project}' },
      { bare: 'that came back wrong', named: 'that came back wrong in {project}' },
      { bare: 'something went bang', named: 'something went bang in {project}' },
      { bare: 'reading what it said', named: 'reading what {project} said' },
      { bare: 'non zero, looking now', named: 'non zero in {project}, looking now' },
      { bare: 'that did not work', named: 'that did not work in {project}' },
      { bare: 'the output is red', named: 'the output from {project} is red' },
      { bare: 'going through the error', named: 'going through the error in {project}' },
      { bare: 'something is broken here', named: 'something is broken in {project}' },
      { bare: 'that threw', named: 'that threw in {project}' },
      { bare: 'unpacking the failure', named: 'unpacking the failure in {project}' },
      { bare: 'not the result I expected', named: 'not the result I expected from {project}' },
      { bare: 'looking at the trace', named: 'looking at the trace from {project}' },
      { bare: 'that command hated it', named: 'that command in {project} hated it' },
      { bare: 'reading the message properly', named: 'reading the {project} message properly' },
      { bare: 'failed, finding out why', named: 'failed in {project}, finding out why' },
      { bare: 'an error I need to read', named: 'an error in {project} I need to read' },
      { bare: 'that went badly', named: 'that went badly in {project}' },
      { bare: 'the shell is unhappy', named: 'the shell in {project} is unhappy' },
      { bare: 'working out what broke', named: 'working out what broke in {project}' },
      { bare: 'reading rather than retrying', named: 'reading the {project} output rather than retrying' },
      { bare: 'something upstream failed', named: 'something upstream of {project} failed' },
      { bare: 'checking the actual error', named: 'checking the actual error in {project}' },
      { bare: 'that needs a closer look', named: 'that needs a closer look in {project}' },
      { bare: 'the command disagreed', named: 'the command in {project} disagreed' },
      { bare: 'not clean. investigating', named: '{project} is not clean. investigating' },
      { bare: 'reading the whole output', named: 'reading the whole output from {project}' },
      { bare: 'finding the real cause', named: 'finding the real cause in {project}' },
      { bare: 'that is a genuine error', named: 'that is a genuine error in {project}' },
      { bare: 'looking past the first line', named: 'looking past the first line of the {project} output' },
      { bare: 'diagnosing this one', named: 'diagnosing this one in {project}' },
      { bare: 'the trace has the answer', named: 'the {project} trace has the answer' },
      { bare: 'going to understand it first', named: 'going to understand {project} first' },
      { bare: 'not guessing at this', named: 'not guessing at this one in {project}' },
      { bare: 'that failed loudly', named: 'that failed loudly in {project}' },
      { bare: 'something needs fixing', named: 'something in {project} needs fixing' },
      { bare: 'reading before acting', named: 'reading the {project} output before acting' },
      { bare: 'error understood, mostly', named: 'the {project} error is understood, mostly' },
      { bare: 'getting to the bottom of it', named: 'getting to the bottom of it in {project}' },
      { bare: 'that will need a change', named: 'that will need a change in {project}' }
    ]
  },
  {
    id: 'no-matches',
    tier: 'chatter',
    // "Failed with non-blocking status code" is a PreToolUse hook complaint, not
    // the agent mistyping a glob: it accounted for 130 of the hits on a replay of
    // 285k captured buffer lines, every one of them a false positive.
    pattern: /^(?!.*Failed with non-blocking).*(?:no matches found|command not found|No such file or directory)/i,
    emote: 'sheepish',
    cooldownMs: 9000,
    lines: [
      { bare: 'my glob was wrong, not the repo', named: 'my glob was wrong, not {project}' },
      { bare: 'searched for something that is not there', named: 'searched {project} for something that is not there' },
      { bare: 'that was a typo in my own command', named: 'that was a typo in my own command, not {project}' },
      { bare: 'wrong shell quoting again. my bad', named: 'wrong shell quoting in {project} again. my bad' },
      { bare: 'zsh disagrees with how I wrote that', named: 'zsh in {project} disagrees with how I wrote that' },
      { bare: 'fumbled the quoting, retrying', named: 'fumbled the quoting in {project}, retrying' },
      { bare: 'that path does not exist. my error', named: 'that path in {project} does not exist. my error' },
      { bare: 'mistyped it. going again', named: 'mistyped it in {project}. going again' },
      { bare: 'the pattern was wrong, not the code', named: 'the pattern was wrong, not the code in {project}' },
      { bare: 'writing that command properly this time', named: 'writing that {project} command properly this time' },
      { bare: 'nothing there. my mistake', named: 'nothing there in {project}. my mistake' },
      { bare: 'wrong path, trying again', named: 'wrong path in {project}, trying again' },
      { bare: 'that does not exist', named: 'that does not exist in {project}' },
      { bare: 'searched the wrong place', named: 'searched the wrong place in {project}' },
      { bare: 'my pattern was off', named: 'my pattern for {project} was off' },
      { bare: 'bad glob, rewriting it', named: 'bad glob in {project}, rewriting it' },
      { bare: 'the quoting got me', named: 'the quoting in {project} got me' },
      { bare: 'nothing matched, my fault', named: 'nothing matched in {project}, my fault' },
      { bare: 'that spelling was wrong', named: 'that spelling was wrong for {project}' },
      { bare: 'looking in the wrong spot', named: 'looking in the wrong spot in {project}' },
      { bare: 'no such file, apparently', named: 'no such file in {project}, apparently' },
      { bare: 'retyping that properly', named: 'retyping that properly for {project}' },
      { bare: 'the shell ate my quotes', named: 'the shell in {project} ate my quotes' },
      { bare: 'wrong syntax again', named: 'wrong syntax again in {project}' },
      { bare: 'that command does not exist here', named: 'that command does not exist in {project}' },
      { bare: 'missed the path', named: 'missed the path in {project}' },
      { bare: 'checking where it actually lives', named: 'checking where it actually lives in {project}' },
      { bare: 'correcting my own typo', named: 'correcting my own typo in {project}' },
      { bare: 'that was user error, mine', named: 'that was my error, not {project}' },
      { bare: 'searching properly this time', named: 'searching {project} properly this time' },
      { bare: 'empty result, my doing', named: 'empty result in {project}, my doing' },
      { bare: 'the glob needs fixing', named: 'the glob for {project} needs fixing' },
      { bare: 'wrong directory entirely', named: 'wrong directory in {project} entirely' },
      { bare: 'that was never going to match', named: 'that was never going to match in {project}' },
      { bare: 'adjusting the pattern', named: 'adjusting the pattern for {project}' },
      { bare: 'my search was too narrow', named: 'my search of {project} was too narrow' },
      { bare: 'looking somewhere real now', named: 'looking somewhere real in {project} now' },
      { bare: 'fixing how I wrote that', named: 'fixing how I wrote that for {project}' },
      { bare: 'no hits, trying differently', named: 'no hits in {project}, trying differently' },
      { bare: 'that argument was wrong', named: 'that argument was wrong for {project}' },
      { bare: 'rewriting the command', named: 'rewriting the command for {project}' },
      { bare: 'the path had a typo', named: 'the path into {project} had a typo' },
      { bare: 'not the repo, me', named: 'not {project}, me' },
      { bare: 'trying a wider net', named: 'trying a wider net across {project}' },
      { bare: 'that was badly quoted', named: 'that was badly quoted in {project}' },
      { bare: 'going again, carefully', named: 'going again in {project}, carefully' },
      { bare: 'checking the spelling first', named: 'checking the spelling in {project} first' },
      { bare: 'missed by a character', named: 'missed by a character in {project}' },
      { bare: 'searching the right tree now', named: 'searching the right part of {project} now' }
    ]
  },
  {
    id: 'tests-passed',
    tier: 'outcome',
    pattern: /\b\d+ (?:passed|passing)\b|✓\s+\d+ tests?/i,
    emote: 'happy',
    soundId: 'correct-tone',
    cooldownMs: 8000,
    lines: [
      { bare: 'green. all of it', named: '{project} is green, all of it' },
      { bare: 'tests pass, we are fine', named: 'tests pass in {project}, we are fine' },
      { bare: 'that is the good colour', named: 'that is the good colour in {project}' },
      { bare: 'suite is happy', named: 'the suite in {project} is happy' },
      { bare: 'passed. moving on', named: '{project} passed. moving on' },
      { bare: 'all green, nothing to argue with', named: '{project} is all green, nothing to argue with' },
      { bare: 'suite agrees with the change', named: 'the suite in {project} agrees with the change' },
      { bare: 'passing. that is the bar cleared', named: '{project} is passing. that is the bar cleared' },
      { bare: 'no failures to report', named: 'no failures to report in {project}' },
      { bare: 'green across the board', named: '{project} is green across the board' },
      { bare: 'all passing', named: 'everything in {project} is passing' },
      { bare: 'green, every one', named: '{project} is green, every one' },
      { bare: 'suite is clean', named: 'the suite in {project} is clean' },
      { bare: 'nothing failing', named: 'nothing failing in {project}' },
      { bare: 'that went through', named: 'that went through in {project}' },
      { bare: 'tests are satisfied', named: 'the tests in {project} are satisfied' },
      { bare: 'clean run', named: 'clean run in {project}' },
      { bare: 'no red anywhere', named: 'no red anywhere in {project}' },
      { bare: 'passing properly', named: '{project} is passing properly' },
      { bare: 'the suite approves', named: 'the suite in {project} approves' },
      { bare: 'everything holds', named: 'everything in {project} holds' },
      { bare: 'that checks out', named: 'that checks out in {project}' },
      { bare: 'green light', named: 'green light on {project}' },
      { bare: 'no objections from the tests', named: 'no objections from the tests in {project}' },
      { bare: 'all of them pass', named: 'all of them pass in {project}' },
      { bare: 'that change is safe', named: 'that change in {project} is safe' },
      { bare: 'tests back me up', named: 'the tests in {project} back me up' },
      { bare: 'clean, genuinely', named: '{project} is clean, genuinely' },
      { bare: 'nothing broke', named: 'nothing broke in {project}' },
      { bare: 'the suite is quiet', named: 'the suite in {project} is quiet' },
      { bare: 'passing without drama', named: '{project} is passing without drama' },
      { bare: 'all clear', named: 'all clear in {project}' },
      { bare: 'no failures at all', named: 'no failures at all in {project}' },
      { bare: 'that held up', named: 'that held up in {project}' },
      { bare: 'tests happy with it', named: 'the tests in {project} are happy with it' },
      { bare: 'green the whole way', named: '{project} is green the whole way' },
      { bare: 'nothing to fix here', named: 'nothing to fix in {project}' },
      { bare: 'the suite signed off', named: 'the suite in {project} signed off' },
      { bare: 'passed on the first go', named: '{project} passed on the first go' },
      { bare: 'clean result', named: 'clean result in {project}' },
      { bare: 'no complaints anywhere', named: 'no complaints anywhere in {project}' },
      { bare: 'that works then', named: 'that works in {project} then' },
      { bare: 'everything still passes', named: 'everything in {project} still passes' },
      { bare: 'the change did not break anything', named: 'the change did not break anything in {project}' },
      { bare: 'green and staying green', named: '{project} is green and staying green' },
      { bare: 'all good', named: 'all good in {project}' },
      { bare: 'suite says yes', named: 'the suite in {project} says yes' },
      { bare: 'tested and fine', named: '{project} is tested and fine' },
      { bare: 'that is done properly', named: 'that is done properly in {project}' }
    ]
  },
  {
    id: 'typecheck-clean',
    tier: 'outcome',
    pattern: /Found 0 errors|No errors found|Typecheck (?:clean|passes|is clean)|compiled successfully/i,
    emote: 'proud',
    soundId: 'correct-tone',
    cooldownMs: 10000,
    lines: [
      { bare: 'typechecker is happy', named: 'the typechecker is happy with {project}' },
      { bare: 'clean. genuinely clean', named: '{project} is clean, genuinely clean' },
      { bare: 'zero errors, I will take it', named: 'zero errors in {project}, I will take it' },
      { bare: 'types agree with me for once', named: 'the types in {project} agree with me for once' },
      { bare: 'no complaints from tsc', named: 'no complaints from tsc about {project}' },
      { bare: 'compiles without argument', named: '{project} compiles without argument' },
      { bare: 'types line up', named: 'the types in {project} line up' },
      { bare: 'nothing for the compiler to say', named: 'nothing for the compiler to say about {project}' },
      { bare: 'clean build, no notes', named: 'clean build in {project}, no notes' },
      { bare: 'tsc has no opinion today', named: 'tsc has no opinion about {project} today' },
      { bare: 'types are fine', named: 'the types in {project} are fine' },
      { bare: 'no errors at all', named: 'no errors at all in {project}' },
      { bare: 'the compiler is quiet', named: 'the compiler is quiet about {project}' },
      { bare: 'clean typecheck', named: 'clean typecheck in {project}' },
      { bare: 'nothing for tsc to say', named: 'nothing for tsc to say about {project}' },
      { bare: 'types check out', named: 'the types in {project} check out' },
      { bare: 'compiled without complaint', named: '{project} compiled without complaint' },
      { bare: 'zero problems', named: 'zero problems in {project}' },
      { bare: 'that all lines up', named: 'that all lines up in {project}' },
      { bare: 'no type errors', named: 'no type errors in {project}' },
      { bare: 'the compiler agrees', named: 'the compiler agrees with {project}' },
      { bare: 'types are consistent', named: 'the types in {project} are consistent' },
      { bare: 'clean, no warnings', named: '{project} is clean, no warnings' },
      { bare: 'nothing flagged', named: 'nothing flagged in {project}' },
      { bare: 'typechecker had nothing', named: 'the typechecker had nothing on {project}' },
      { bare: 'all types resolve', named: 'all the types in {project} resolve' },
      { bare: 'compiles cleanly', named: '{project} compiles cleanly' },
      { bare: 'no signature mismatches', named: 'no signature mismatches in {project}' },
      { bare: 'that types properly', named: 'that types properly in {project}' },
      { bare: 'the checker is satisfied', named: 'the checker is satisfied with {project}' },
      { bare: 'no complaints today', named: 'no complaints about {project} today' },
      { bare: 'everything typed correctly', named: 'everything in {project} typed correctly' },
      { bare: 'clean on the first pass', named: '{project} was clean on the first pass' },
      { bare: 'no errors reported', named: 'no errors reported in {project}' },
      { bare: 'types agree throughout', named: 'the types in {project} agree throughout' },
      { bare: 'nothing to correct', named: 'nothing to correct in {project}' },
      { bare: 'the build is clean', named: 'the build in {project} is clean' },
      { bare: 'compiler found nothing', named: 'the compiler found nothing in {project}' },
      { bare: 'typed and fine', named: '{project} is typed and fine' },
      { bare: 'all good on types', named: 'all good on types in {project}' },
      { bare: 'no red from tsc', named: 'no red from tsc on {project}' },
      { bare: 'that compiles', named: 'that compiles in {project}' },
      { bare: 'clean output', named: 'clean output from {project}' },
      { bare: 'no issues raised', named: 'no issues raised in {project}' },
      { bare: 'types hold together', named: 'the types in {project} hold together' },
      { bare: 'nothing broken there', named: 'nothing broken in {project}' },
      { bare: 'checker passed it', named: 'the checker passed {project}' },
      { bare: 'no problems found', named: 'no problems found in {project}' },
      { bare: 'compiled first time', named: '{project} compiled first time' }
    ]
  },
  {
    id: 'git-commit',
    tier: 'outcome',
    pattern: /^\[[\w./-]+ [0-9a-f]{7,}\]|\b\d+ files? changed|Committed as\b/,
    emote: 'proud',
    soundId: 'confirmation',
    cooldownMs: 5000,
    lines: [
      { bare: 'committed. that one is safe now', named: 'committed in {project}. that one is safe now' },
      { bare: 'snapshot taken', named: 'snapshot taken in {project}' },
      { bare: 'on the record', named: 'that is on the record in {project}' },
      { bare: 'saved to history', named: 'saved to history in {project}' },
      { bare: 'that is locked in', named: 'that is locked into {project}' },
      { bare: 'written to the log', named: 'written to the log in {project}' },
      { bare: 'committed. recoverable now', named: 'committed in {project}. recoverable now' },
      { bare: 'that work has a hash', named: 'that work in {project} has a hash now' },
      { bare: 'banked, moving on', named: 'banked in {project}, moving on' },
      { bare: 'safely in history', named: 'safely in the {project} history' },
      { bare: 'that is committed', named: 'that is committed in {project}' },
      { bare: 'saved properly', named: 'saved properly in {project}' },
      { bare: 'in the history now', named: 'in the {project} history now' },
      { bare: 'written down', named: 'written down in {project}' },
      { bare: 'safe in git', named: 'safe in git, over in {project}' },
      { bare: 'that has a hash now', named: 'that has a hash in {project} now' },
      { bare: 'recorded properly', named: 'recorded properly in {project}' },
      { bare: 'committed cleanly', named: 'committed cleanly in {project}' },
      { bare: 'stored away', named: 'stored away in {project}' },
      { bare: 'that is permanent now', named: 'that is permanent in {project} now' },
      { bare: 'on disk and in history', named: 'on disk and in the {project} history' },
      { bare: 'work preserved', named: 'the work in {project} is preserved' },
      { bare: 'commit made', named: 'commit made in {project}' },
      { bare: 'that will not get lost', named: 'that will not get lost in {project}' },
      { bare: 'logged in git', named: 'logged in git, over in {project}' },
      { bare: 'change captured', named: 'the change in {project} is captured' },
      { bare: 'that is checkpointed', named: 'that is checkpointed in {project}' },
      { bare: 'saved for good', named: 'saved for good in {project}' },
      { bare: 'history updated', named: 'the {project} history is updated' },
      { bare: 'that one is recoverable', named: 'that one in {project} is recoverable' },
      { bare: 'committed and safe', named: 'committed and safe in {project}' },
      { bare: 'written to the branch', named: 'written to the branch in {project}' },
      { bare: 'progress saved', named: 'progress in {project} is saved' },
      { bare: 'that is filed away', named: 'that is filed away in {project}' },
      { bare: 'the tree is clean again', named: 'the tree in {project} is clean again' },
      { bare: 'change is recorded', named: 'the change in {project} is recorded' },
      { bare: 'committed without fuss', named: 'committed without fuss in {project}' },
      { bare: 'that is in the log', named: 'that is in the {project} log' },
      { bare: 'safely stored', named: 'safely stored in {project}' },
      { bare: 'work is banked', named: 'the work in {project} is banked' },
      { bare: 'the commit landed', named: 'the commit landed in {project}' },
      { bare: 'history has it now', named: 'the {project} history has it now' },
      { bare: 'that survives a reboot', named: 'that survives a reboot in {project}' },
      { bare: 'saved to the branch', named: 'saved to the branch in {project}' },
      { bare: 'commit written', named: 'commit written in {project}' },
      { bare: 'that is on record', named: 'that is on record in {project}' },
      { bare: 'change is locked down', named: 'the change in {project} is locked down' },
      { bare: 'git has it', named: 'git has it, over in {project}' },
      { bare: 'done and committed', named: 'done and committed in {project}' }
    ]
  },
  {
    id: 'asking-user',
    tier: 'attention',
    // The permission box is the most common "stopped, needs you" moment, and the
    // old pattern missed it entirely. Not anchored on ❯: the buffer feed strips
    // that as gutter padding and drops bare-caret rows as noise.
    // "User answered" is deliberately absent: it is printed once the prompt has
    // been resolved, so matching it announced that a human was needed at exactly
    // the moment one no longer was.
    pattern: /\bDo you want to (?:proceed|make this edit|create)\b|\bWould you like me to\b|\b(?:Which do you want|Tell me which|pick one|your call|say the word)\b/i,
    emote: 'waiting',
    soundId: 'message-pop',
    cooldownMs: 6000,
    attention: true,
    lines: [
      { bare: 'need you for this bit', named: '{project} needs you for this bit' },
      { bare: 'your call, not mine', named: 'your call in {project}, not mine' },
      { bare: 'handing it back', named: 'handing {project} back to you' },
      { bare: 'waiting on a decision', named: 'waiting on a decision in {project}' },
      { bare: 'this one needs a human', named: 'this one in {project} needs a human' },
      { bare: 'stopped, and it is your turn', named: 'stopped in {project}, and it is your turn' },
      { bare: 'cannot pick this one alone', named: 'cannot pick this one in {project} alone' },
      { bare: 'parked until you answer', named: 'parked in {project} until you answer' },
      { bare: 'needs a decision I should not make', named: '{project} needs a decision I should not make' },
      { bare: 'waiting. no rush, but I am stuck', named: 'waiting in {project}. no rush, but I am stuck' },
      { bare: 'over to you', named: 'over to you on {project}' },
      { bare: 'this needs you', named: '{project} needs you' },
      { bare: 'waiting for you', named: 'waiting for you over in {project}' },
      { bare: 'stuck without an answer', named: 'stuck in {project} without an answer' },
      { bare: 'your decision', named: 'your decision on {project}' },
      { bare: 'cannot proceed alone', named: 'cannot proceed in {project} alone' },
      { bare: 'need a steer here', named: 'need a steer on {project}' },
      { bare: 'holding for input', named: 'holding {project} for input' },
      { bare: 'that is above my level', named: 'that one in {project} is above my level' },
      { bare: 'asking rather than guessing', named: 'asking about {project} rather than guessing' },
      { bare: 'paused for you', named: 'paused in {project} for you' },
      { bare: 'need your opinion', named: 'need your opinion on {project}' },
      { bare: 'not going to decide this', named: 'not going to decide this one in {project}' },
      { bare: 'waiting on your word', named: 'waiting on your word for {project}' },
      { bare: 'this one is yours', named: 'this one in {project} is yours' },
      { bare: 'stopped, needs an answer', named: 'stopped in {project}, needs an answer' },
      { bare: 'requires a human call', named: '{project} requires a human call' },
      { bare: 'checking with you first', named: 'checking with you about {project} first' },
      { bare: 'not proceeding without you', named: 'not proceeding in {project} without you' },
      { bare: 'need a yes or no', named: 'need a yes or no on {project}' },
      { bare: 'your judgement, not mine', named: 'your judgement on {project}, not mine' },
      { bare: 'pausing here', named: 'pausing here in {project}' },
      { bare: 'want your take on this', named: 'want your take on this bit of {project}' },
      { bare: 'blocked on a decision', named: 'blocked on a decision in {project}' },
      { bare: 'asking before acting', named: 'asking before acting in {project}' },
      { bare: 'that is your choice to make', named: 'that is your choice to make in {project}' },
      { bare: 'holding until you say', named: 'holding {project} until you say' },
      { bare: 'need direction', named: 'need direction on {project}' },
      { bare: 'stopping to ask', named: 'stopping in {project} to ask' },
      { bare: 'would rather you decided', named: 'would rather you decided this one in {project}' },
      { bare: 'waiting patiently', named: 'waiting patiently over in {project}' },
      { bare: 'this needs a person', named: 'this bit of {project} needs a person' },
      { bare: 'cannot answer that myself', named: 'cannot answer that one in {project} myself' },
      { bare: 'deferring to you', named: 'deferring to you on {project}' },
      { bare: 'need input before continuing', named: 'need input before continuing in {project}' },
      { bare: 'stopped at a fork', named: 'stopped at a fork in {project}' },
      { bare: 'your shout', named: 'your shout on {project}' },
      { bare: 'asking properly rather than assuming', named: 'asking properly about {project} rather than assuming' },
      { bare: 'sitting here waiting', named: 'sitting in {project} waiting' },
      { bare: 'needs a call from you', named: '{project} needs a call from you' }
    ]
  },
  {
    id: 'editing-file',
    tier: 'chatter',
    pattern: /(?:^|[⏺●•*]\s*)(?:Edit|Write|Update|MultiEdit)\(|\bApplied \d+ edit|\bWrote \d+ lines/,
    emote: 'writing',
    soundId: 'bubble-pop',
    cooldownMs: 2500,
    lines: [
      { bare: 'putting the change in', named: 'putting the change into {project}' },
      { bare: 'editing. carefully, mostly', named: 'editing {project}. carefully, mostly' },
      { bare: 'one file, one line, fingers crossed', named: 'one file in {project}, one line, fingers crossed' },
      { bare: 'writing it down', named: 'writing it down in {project}' },
      { bare: 'making the actual change now', named: 'making the actual change in {project} now' },
      { bare: 'touching source. this is the real part', named: 'touching source in {project}. this is the real part' },
      { bare: 'committing the edit to disk', named: 'committing the edit to disk in {project}' },
      { bare: 'changing the file for real', named: 'changing the file in {project} for real' },
      { bare: 'typing into the thing that ships', named: 'typing into the part of {project} that ships' },
      { bare: 'applying it', named: 'applying it to {project}' },
      { bare: 'rewriting this bit', named: 'rewriting this bit of {project}' },
      { bare: 'putting words in the source', named: 'putting words into the {project} source' },
      { bare: 'making the change', named: 'making the change in {project}' },
      { bare: 'writing to the file', named: 'writing to a file in {project}' },
      { bare: 'editing now', named: 'editing {project} now' },
      { bare: 'putting it in', named: 'putting it into {project}' },
      { bare: 'changing the source', named: 'changing the source in {project}' },
      { bare: 'applying the edit', named: 'applying the edit in {project}' },
      { bare: 'typing it out', named: 'typing it out in {project}' },
      { bare: 'updating the file', named: 'updating a file in {project}' },
      { bare: 'writing the fix', named: 'writing the fix into {project}' },
      { bare: 'editing for real', named: 'editing {project} for real' },
      { bare: 'changing actual code', named: 'changing actual code in {project}' },
      { bare: 'putting the change down', named: 'putting the change down in {project}' },
      { bare: 'modifying this one', named: 'modifying this one in {project}' },
      { bare: 'writing the new version', named: 'writing the new version into {project}' },
      { bare: 'editing carefully', named: 'editing {project} carefully' },
      { bare: 'changing what is there', named: 'changing what is there in {project}' },
      { bare: 'making it so', named: 'making it so in {project}' },
      { bare: 'writing the change in', named: 'writing the change into {project}' },
      { bare: 'touching the source now', named: 'touching the {project} source now' },
      { bare: 'doing the actual edit', named: 'doing the actual edit in {project}' },
      { bare: 'putting hands on the code', named: 'putting hands on the {project} code' },
      { bare: 'writing this properly', named: 'writing this properly in {project}' },
      { bare: 'making the edit stick', named: 'making the edit stick in {project}' },
      { bare: 'updating the source', named: 'updating the source in {project}' },
      { bare: 'changing the file now', named: 'changing the file in {project} now' },
      { bare: 'writing it into place', named: 'writing it into place in {project}' },
      { bare: 'editing the real thing', named: 'editing the real thing in {project}' },
      { bare: 'applying what I worked out', named: 'applying what I worked out to {project}' },
      { bare: 'making the change permanent', named: 'making the change in {project} permanent' },
      { bare: 'writing carefully here', named: 'writing carefully in {project}' },
      { bare: 'changing this file', named: 'changing this file in {project}' },
      { bare: 'putting the fix in', named: 'putting the fix into {project}' },
      { bare: 'editing the source directly', named: 'editing the {project} source directly' },
      { bare: 'writing the correction', named: 'writing the correction into {project}' },
      { bare: 'making it match', named: 'making it match in {project}' },
      { bare: 'changing the implementation', named: 'changing the implementation in {project}' },
      { bare: 'writing the update', named: 'writing the update into {project}' },
      { bare: 'editing with intent', named: 'editing {project} with intent' },
      { bare: 'putting the new code in', named: 'putting the new code into {project}' }
    ]
  },
  {
    id: 'searching',
    tier: 'chatter',
    pattern: /(?:^|[⏺●•*]\s*)(?:Grep|Glob|Search)\(|^\s*grep -/,
    emote: 'searching',
    cooldownMs: 3000,
    lines: [
      { bare: 'grepping the haystack', named: 'grepping the haystack in {project}' },
      { bare: 'hunting for where this lives', named: 'hunting for where this lives in {project}' },
      { bare: 'sweeping the tree', named: 'sweeping the {project} tree' },
      { bare: 'looking for the seam', named: 'looking for the seam in {project}' },
      { bare: 'searching. wide net first', named: 'searching {project}. wide net first' },
      { bare: 'finding out if this exists at all', named: 'finding out if this exists in {project} at all' },
      { bare: 'combing through the repo', named: 'combing through {project}' },
      { bare: 'chasing this symbol', named: 'chasing this symbol through {project}' },
      { bare: 'looking for where it is defined', named: 'looking for where it is defined in {project}' },
      { bare: 'casting around the codebase', named: 'casting around {project}' },
      { bare: 'trying to find the other half of this', named: 'trying to find the other half of this in {project}' },
      { bare: 'scanning for callers', named: 'scanning {project} for callers' },
      { bare: 'looking for it', named: 'looking for it in {project}' },
      { bare: 'searching the tree', named: 'searching the {project} tree' },
      { bare: 'finding where this is', named: 'finding where this is in {project}' },
      { bare: 'hunting it down', named: 'hunting it down in {project}' },
      { bare: 'grepping for it', named: 'grepping {project} for it' },
      { bare: 'scanning the files', named: 'scanning the files in {project}' },
      { bare: 'looking through the code', named: 'looking through the {project} code' },
      { bare: 'finding the definition', named: 'finding the definition in {project}' },
      { bare: 'searching properly', named: 'searching {project} properly' },
      { bare: 'casting about', named: 'casting about in {project}' },
      { bare: 'checking if it exists', named: 'checking if it exists in {project}' },
      { bare: 'looking for references', named: 'looking for references in {project}' },
      { bare: 'sweeping for matches', named: 'sweeping {project} for matches' },
      { bare: 'finding every use', named: 'finding every use in {project}' },
      { bare: 'searching wide', named: 'searching {project} wide' },
      { bare: 'looking in the likely places', named: 'looking in the likely places in {project}' },
      { bare: 'tracking this down', named: 'tracking this down in {project}' },
      { bare: 'finding the source of it', named: 'finding the source of it in {project}' },
      { bare: 'scanning for the pattern', named: 'scanning {project} for the pattern' },
      { bare: 'looking for where it starts', named: 'looking for where it starts in {project}' },
      { bare: 'searching the whole repo', named: 'searching the whole of {project}' },
      { bare: 'finding what calls this', named: 'finding what calls this in {project}' },
      { bare: 'hunting for the definition', named: 'hunting for the definition in {project}' },
      { bare: 'looking it up properly', named: 'looking it up properly in {project}' },
      { bare: 'searching before assuming', named: 'searching {project} before assuming' },
      { bare: 'checking what already exists', named: 'checking what already exists in {project}' },
      { bare: 'finding the prior art', named: 'finding the prior art in {project}' },
      { bare: 'looking for something similar', named: 'looking for something similar in {project}' },
      { bare: 'scanning for duplicates', named: 'scanning {project} for duplicates' },
      { bare: 'searching the imports', named: 'searching the imports in {project}' },
      { bare: 'finding out where this lives', named: 'finding out where this lives in {project}' },
      { bare: 'looking through for context', named: 'looking through {project} for context' },
      { bare: 'grepping around', named: 'grepping around in {project}' },
      { bare: 'searching for the pattern', named: 'searching {project} for the pattern' },
      { bare: 'checking every match', named: 'checking every match in {project}' },
      { bare: 'looking for the connection', named: 'looking for the connection in {project}' },
      { bare: 'finding the other end', named: 'finding the other end in {project}' },
      { bare: 'searching methodically', named: 'searching {project} methodically' },
      { bare: 'combing for it', named: 'combing {project} for it' }
    ]
  },
  {
    id: 'reading-file',
    tier: 'chatter',
    pattern: /(?:^|[⏺●•*]\s*)Read\(|\bRead \d+ lines\b/,
    emote: 'reading',
    cooldownMs: 2500,
    lines: [
      { bare: 'skimming this one', named: 'skimming this one in {project}' },
      { bare: 'eyes on the file', named: 'eyes on a file in {project}' },
      { bare: 'reading before touching anything', named: 'reading {project} before touching anything' },
      { bare: 'loading context', named: 'loading context from {project}' },
      { bare: 'having a look at what is actually there', named: 'having a look at what is actually in {project}' },
      { bare: 'checking the source instead of guessing', named: 'checking the {project} source instead of guessing' },
      { bare: 'reading it properly first', named: 'reading {project} properly first' },
      { bare: 'getting the shape of this file', named: 'getting the shape of this file in {project}' },
      { bare: 'working out what is already here', named: 'working out what is already in {project}' },
      { bare: 'reading rather than assuming', named: 'reading {project} rather than assuming' },
      { bare: 'taking this one in', named: 'taking this one in, over in {project}' },
      { bare: 'seeing how it is done here', named: 'seeing how it is done in {project}' },
      { bare: 'reading this one', named: 'reading this one in {project}' },
      { bare: 'having a look', named: 'having a look at {project}' },
      { bare: 'taking it in', named: 'taking in what {project} does' },
      { bare: 'reading through', named: 'reading through {project}' },
      { bare: 'looking at the code', named: 'looking at the {project} code' },
      { bare: 'skimming for context', named: 'skimming {project} for context' },
      { bare: 'reading properly', named: 'reading {project} properly' },
      { bare: 'getting the picture', named: 'getting the picture in {project}' },
      { bare: 'looking at what exists', named: 'looking at what exists in {project}' },
      { bare: 'reading the source', named: 'reading the {project} source' },
      { bare: 'checking what is here', named: 'checking what is in {project}' },
      { bare: 'going through the file', named: 'going through a file in {project}' },
      { bare: 'reading before deciding', named: 'reading {project} before deciding' },
      { bare: 'absorbing this', named: 'absorbing this bit of {project}' },
      { bare: 'looking at how it works', named: 'looking at how {project} works' },
      { bare: 'reading the implementation', named: 'reading the implementation in {project}' },
      { bare: 'seeing what it does', named: 'seeing what {project} does here' },
      { bare: 'getting familiar with this', named: 'getting familiar with this part of {project}' },
      { bare: 'reading the whole thing', named: 'reading the whole thing in {project}' },
      { bare: 'checking the current state', named: 'checking the current state of {project}' },
      { bare: 'looking at the existing code', named: 'looking at the existing {project} code' },
      { bare: 'reading the conventions here', named: 'reading the conventions in {project}' },
      { bare: 'understanding the file first', named: 'understanding the {project} file first' },
      { bare: 'taking a look inside', named: 'taking a look inside {project}' },
      { bare: 'reading it end to end', named: 'reading it end to end in {project}' },
      { bare: 'seeing how this is built', named: 'seeing how {project} is built' },
      { bare: 'checking before changing', named: 'checking {project} before changing it' },
      { bare: 'reading for the pattern', named: 'reading {project} for the pattern' },
      { bare: 'looking at the structure', named: 'looking at the structure of {project}' },
      { bare: 'going over it', named: 'going over it in {project}' },
      { bare: 'reading the surrounding code', named: 'reading the surrounding code in {project}' },
      { bare: 'getting the shape of it', named: 'getting the shape of {project}' },
      { bare: 'studying this briefly', named: 'studying this bit of {project} briefly' },
      { bare: 'reading what is written', named: 'reading what is written in {project}' },
      { bare: 'checking the real behaviour', named: 'checking the real behaviour in {project}' },
      { bare: 'looking properly this time', named: 'looking at {project} properly this time' },
      { bare: 'going through it carefully', named: 'going through {project} carefully' },
      { bare: 'taking in the context', named: 'taking in the context in {project}' }
    ]
  },
  {
    id: 'running-command',
    tier: 'chatter',
    pattern: /(?:^|[⏺●•*]\s*)Bash\(|^\s*(?:npm|npx|yarn|pnpm) (?:run |exec )?\S+/,
    emote: 'running',
    cooldownMs: 3000,
    lines: [
      { bare: 'shelling out', named: 'I am shelling out in {project}' },
      { bare: 'running it and watching', named: 'running it in {project} and watching' },
      { bare: 'let us see what the machine says', named: 'let us see what {project} says' },
      { bare: 'command away', named: 'command away in {project}' },
      { bare: 'firing this off', named: 'firing this off in {project}' },
      { bare: 'hoping the exit code is zero', named: 'hoping {project} comes back with a zero' },
      { bare: 'handing this to the shell', named: 'handing this to the shell in {project}' },
      { bare: 'running it for real', named: 'running it for real in {project}' },
      { bare: 'waiting on the output', named: 'waiting on output from {project}' },
      { bare: 'off to the terminal', named: 'off to the terminal in {project}' },
      { bare: 'executing and hoping', named: 'executing in {project} and hoping' },
      { bare: 'watching this one run', named: 'watching this one run in {project}' },
      { bare: 'running it', named: 'running it in {project}' },
      { bare: 'off to the shell', named: 'off to the shell in {project}' },
      { bare: 'executing now', named: 'executing in {project} now' },
      { bare: 'kicking it off', named: 'kicking it off in {project}' },
      { bare: 'running the command', named: 'running the command in {project}' },
      { bare: 'sending it to bash', named: 'sending it to bash in {project}' },
      { bare: 'starting that up', named: 'starting that up in {project}' },
      { bare: 'letting it run', named: 'letting it run in {project}' },
      { bare: 'watching the output', named: 'watching the output from {project}' },
      { bare: 'running and waiting', named: 'running in {project} and waiting' },
      { bare: 'invoking it', named: 'invoking it in {project}' },
      { bare: 'firing the command', named: 'firing the command in {project}' },
      { bare: 'running this through', named: 'running this through {project}' },
      { bare: 'giving that a go', named: 'giving that a go in {project}' },
      { bare: 'executing and watching', named: 'executing in {project} and watching' },
      { bare: 'starting the run', named: 'starting the run in {project}' },
      { bare: 'putting it through the shell', named: 'putting it through the shell in {project}' },
      { bare: 'seeing what comes back', named: 'seeing what comes back from {project}' },
      { bare: 'running it properly', named: 'running it properly in {project}' },
      { bare: 'waiting on the result', named: 'waiting on the result from {project}' },
      { bare: 'launching that', named: 'launching that in {project}' },
      { bare: 'running to find out', named: 'running it in {project} to find out' },
      { bare: 'testing it for real', named: 'testing it for real in {project}' },
      { bare: 'letting the machine answer', named: 'letting {project} answer for itself' },
      { bare: 'running the real thing', named: 'running the real thing in {project}' },
      { bare: 'kicking off the process', named: 'kicking off the process in {project}' },
      { bare: 'shell time', named: 'shell time in {project}' },
      { bare: 'running it now', named: 'running it in {project} now' },
      { bare: 'waiting for the exit code', named: 'waiting for the exit code from {project}' },
      { bare: 'watching it work', named: 'watching it work in {project}' },
      { bare: 'sending that off', named: 'sending that off in {project}' },
      { bare: 'running and hoping', named: 'running in {project} and hoping' },
      { bare: 'getting the answer from the shell', named: 'getting the answer from the shell in {project}' },
      { bare: 'executing the command', named: 'executing the command in {project}' },
      { bare: 'seeing if it works', named: 'seeing if it works in {project}' },
      { bare: 'running it live', named: 'running it live in {project}' },
      { bare: 'starting it going', named: 'starting it going in {project}' },
      { bare: 'handing over to bash', named: 'handing over to bash in {project}' },
      { bare: 'running to confirm', named: 'running it in {project} to confirm' }
    ]
  },
  {
    id: 'long-thinking',
    tier: 'chatter',
    pattern: /^(?:Let me|I need to|Before (?:firing|writing)|Privately,|What I (?:still )?need)/,
    emote: 'thinking',
    cooldownMs: 4000,
    lines: [
      { bare: 'working out the order of this', named: 'working out the order of this in {project}' },
      { bare: 'thinking before typing', named: 'thinking before typing in {project}' },
      { bare: 'planning the next couple of moves', named: 'planning the next couple of moves in {project}' },
      { bare: 'figuring out what I actually need', named: 'figuring out what I actually need in {project}' },
      { bare: 'holding on, reasoning', named: 'holding on in {project}, reasoning' },
      { bare: 'deciding what matters here', named: 'deciding what matters in {project}' },
      { bare: 'lining the steps up', named: 'lining the steps up for {project}' },
      { bare: 'thinking this through first', named: 'thinking {project} through first' },
      { bare: 'working out what comes first', named: 'working out what comes first in {project}' },
      { bare: 'sizing this up before starting', named: 'sizing {project} up before starting' },
      { bare: 'turning it over', named: 'turning {project} over in my head' },
      { bare: 'sorting out the approach', named: 'sorting out the approach for {project}' },
      { bare: 'thinking it over', named: 'thinking {project} over' },
      { bare: 'working it out', named: 'working {project} out' },
      { bare: 'planning this', named: 'planning this bit of {project}' },
      { bare: 'considering the order', named: 'considering the order in {project}' },
      { bare: 'thinking it through', named: 'thinking {project} through' },
      { bare: 'working out the approach', named: 'working out the approach in {project}' },
      { bare: 'planning ahead a bit', named: 'planning ahead a bit in {project}' },
      { bare: 'sorting the steps', named: 'sorting the steps for {project}' },
      { bare: 'thinking about what matters', named: 'thinking about what matters in {project}' },
      { bare: 'weighing the options', named: 'weighing the options in {project}' },
      { bare: 'deciding how to start', named: 'deciding how to start in {project}' },
      { bare: 'mapping it out', named: 'mapping out the work in {project}' },
      { bare: 'working through the problem', named: 'working through the problem in {project}' },
      { bare: 'considering what to do', named: 'considering what to do in {project}' },
      { bare: 'reasoning about this', named: 'reasoning about this bit of {project}' },
      { bare: 'planning the change', named: 'planning the change in {project}' },
      { bare: 'thinking before moving', named: 'thinking before moving in {project}' },
      { bare: 'working out the shape', named: 'working out the shape of this in {project}' },
      { bare: 'considering the trade offs', named: 'considering the trade offs in {project}' },
      { bare: 'deciding the order', named: 'deciding the order in {project}' },
      { bare: 'looking at this properly', named: 'looking at {project} properly' },
      { bare: 'thinking about consequences', named: 'thinking about the consequences in {project}' },
      { bare: 'planning the next step', named: 'planning the next step in {project}' },
      { bare: 'working out what is needed', named: 'working out what {project} needs' },
      { bare: 'considering the alternatives', named: 'considering the alternatives in {project}' },
      { bare: 'thinking carefully here', named: 'thinking carefully about {project}' },
      { bare: 'sizing up the work', named: 'sizing up the work in {project}' },
      { bare: 'planning before typing', named: 'planning {project} before typing' },
      { bare: 'working out the sequence', named: 'working out the sequence in {project}' },
      { bare: 'deciding what to touch', named: 'deciding what to touch in {project}' },
      { bare: 'thinking about the design', named: 'thinking about the design in {project}' },
      { bare: 'considering how this fits', named: 'considering how this fits into {project}' },
      { bare: 'reasoning it through', named: 'reasoning it through in {project}' },
      { bare: 'planning properly', named: 'planning {project} properly' },
      { bare: 'working out the dependencies', named: 'working out the dependencies in {project}' },
      { bare: 'thinking about the edges', named: 'thinking about the edges in {project}' },
      { bare: 'deciding the approach', named: 'deciding the approach for {project}' },
      { bare: 'taking a moment on this', named: 'taking a moment on this bit of {project}' }
    ]
  },
  {
    id: 'admitting-wrong',
    tier: 'chatter',
    pattern: /\bI was wrong\b|\bmy (?:mistake|bad)\b|\bI (?:mis)?read (?:the|that) wrong\b|contradicts what I/i,
    emote: 'sheepish',
    soundId: 'interface-hint',
    cooldownMs: 12000,
    lines: [
      { bare: 'ok that was me, not the code', named: 'ok, that was me, not {project}' },
      { bare: 'wrong twice, saying so out loud', named: 'wrong twice in {project}, saying so out loud' },
      { bare: 'I had that backwards', named: 'I had that backwards in {project}' },
      { bare: 'correcting myself, sorry', named: 'correcting myself on {project}, sorry' },
      { bare: 'bad call earlier. fixing the reasoning', named: 'bad call in {project} earlier. fixing the reasoning' },
      { bare: 'that was my mistake, not yours', named: 'that was my mistake in {project}, not yours' },
      { bare: 'walking that back', named: 'walking that back in {project}' },
      { bare: 'wrong. saying so rather than hiding it', named: 'wrong about {project}. saying so rather than hiding it' },
      { bare: 'misread it earlier. fixing that now', named: 'misread {project} earlier. fixing that now' },
      { bare: 'owning that one', named: 'owning that one in {project}' },
      { bare: 'that was my error', named: 'that was my error in {project}' },
      { bare: 'I got that wrong', named: 'I got that wrong in {project}' },
      { bare: 'my mistake entirely', named: 'my mistake in {project} entirely' },
      { bare: 'correcting that now', named: 'correcting that in {project} now' },
      { bare: 'wrong, and saying so', named: 'wrong about {project}, and saying so' },
      { bare: 'that was on me', named: 'that one in {project} was on me' },
      { bare: 'misread it, sorry', named: 'misread {project}, sorry' },
      { bare: 'got that backwards', named: 'got that backwards in {project}' },
      { bare: 'my error, fixing it', named: 'my error in {project}, fixing it' },
      { bare: 'that was a bad call', named: 'that was a bad call in {project}' },
      { bare: 'saying so rather than hiding it', named: 'saying so about {project} rather than hiding it' },
      { bare: 'wrong about that', named: 'wrong about that in {project}' },
      { bare: 'owning the mistake', named: 'owning the mistake in {project}' },
      { bare: 'correcting my reasoning', named: 'correcting my reasoning about {project}' },
      { bare: 'I had it wrong', named: 'I had {project} wrong' },
      { bare: 'that was careless', named: 'that was careless of me in {project}' },
      { bare: 'flagging my own error', named: 'flagging my own error in {project}' },
      { bare: 'mistaken, fixing now', named: 'mistaken about {project}, fixing now' },
      { bare: 'my reading was wrong', named: 'my reading of {project} was wrong' },
      { bare: 'that assumption was bad', named: 'that assumption about {project} was bad' },
      { bare: 'wrong on that point', named: 'wrong on that point in {project}' },
      { bare: 'admitting the slip', named: 'admitting the slip in {project}' },
      { bare: 'that was poor reasoning', named: 'that was poor reasoning about {project}' },
      { bare: 'correcting course', named: 'correcting course in {project}' },
      { bare: 'my fault, not the code', named: 'my fault, not {project}' },
      { bare: 'got ahead of myself', named: 'got ahead of myself in {project}' },
      { bare: 'that was wrong of me', named: 'that was wrong of me in {project}' },
      { bare: 'revising what I said', named: 'revising what I said about {project}' },
      { bare: 'taking that back', named: 'taking back what I said about {project}' },
      { bare: 'I was mistaken there', named: 'I was mistaken about {project} there' },
      { bare: 'wrong conclusion, sorry', named: 'wrong conclusion about {project}, sorry' },
      { bare: 'fixing my own error', named: 'fixing my own error in {project}' },
      { bare: 'that was a misread', named: 'that was a misread of {project}' },
      { bare: 'my bad call earlier', named: 'my bad call in {project} earlier' },
      { bare: 'correcting the record', named: 'correcting the record on {project}' },
      { bare: 'wrong, plainly', named: 'wrong about {project}, plainly' },
      { bare: 'that needs walking back', named: 'that needs walking back in {project}' },
      { bare: 'I misjudged that', named: 'I misjudged that in {project}' },
      { bare: 'saying it plainly, wrong', named: 'saying it plainly, I was wrong about {project}' }
    ]
  },
  {
    id: 'idle',
    tier: 'attention',
    // Never matches by design. Going quiet is the absence of output, so there is
    // no line to match on: the feed drops anything under three characters, which
    // is why the old /^$/ pattern here had never once fired. The lines below are
    // real and used; CompanionDock reaches them through a timer instead.
    pattern: /(?!)/,
    emote: 'sleeping',
    soundId: DEFAULT_IDLE_SOUND_ID,
    cooldownMs: 30000,
    lines: [
      { bare: 'done for now', named: 'done with {project} for now' },
      { bare: 'idle. ping me', named: 'idle on {project}. ping me' },
      { bare: 'standing by', named: 'standing by on {project}' },
      { bare: 'nothing left in the queue', named: 'nothing left in the {project} queue' },
      { bare: 'resting until you need something', named: 'resting on {project} until you need something' },
      { bare: 'finished, waiting on you', named: 'finished in {project}, waiting on you' },
      { bare: 'quiet here', named: 'quiet over in {project}' },
      { bare: 'all done. your move', named: '{project} is done. your move' },
      { bare: 'nothing running', named: 'nothing running in {project}' },
      { bare: 'waiting for the next one', named: 'waiting for the next thing in {project}' },
      { bare: 'nothing to do', named: 'nothing to do in {project}' },
      { bare: 'waiting on you', named: 'waiting on you over in {project}' },
      { bare: 'all quiet', named: 'all quiet in {project}' },
      { bare: 'finished here', named: 'finished in {project}' },
      { bare: 'standing by for you', named: 'standing by on {project} for you' },
      { bare: 'no work left', named: 'no work left in {project}' },
      { bare: 'done and waiting', named: 'done with {project} and waiting' },
      { bare: 'idle for now', named: 'idle on {project} for now' },
      { bare: 'queue is empty', named: 'the {project} queue is empty' },
      { bare: 'resting a moment', named: 'resting a moment on {project}' },
      { bare: 'all finished', named: '{project} is all finished' },
      { bare: 'nothing in progress', named: 'nothing in progress in {project}' },
      { bare: 'at a stop', named: 'at a stop in {project}' },
      { bare: 'waiting for work', named: 'waiting for work in {project}' },
      { bare: 'quiet for now', named: '{project} is quiet for now' },
      { bare: 'no tasks left', named: 'no tasks left in {project}' },
      { bare: 'done for the moment', named: 'done with {project} for the moment' },
      { bare: 'sitting idle', named: 'sitting idle in {project}' },
      { bare: 'nothing pending', named: 'nothing pending in {project}' },
      { bare: 'ready when you are', named: 'ready on {project} when you are' },
      { bare: 'work is finished', named: 'the work in {project} is finished' },
      { bare: 'waiting for the next thing', named: 'waiting for the next thing in {project}' },
      { bare: 'all done here', named: 'all done in {project}' },
      { bare: 'nothing on', named: 'nothing on in {project}' },
      { bare: 'paused and waiting', named: 'paused in {project} and waiting' },
      { bare: 'no more to do', named: 'no more to do in {project}' },
      { bare: 'finished the lot', named: 'finished the lot in {project}' },
      { bare: 'awaiting instruction', named: 'awaiting instruction on {project}' },
      { bare: 'clear queue', named: 'the {project} queue is clear' },
      { bare: 'nothing left running', named: 'nothing left running in {project}' },
      { bare: 'done, ping me', named: 'done with {project}, ping me' },
      { bare: 'waiting quietly', named: 'waiting quietly on {project}' },
      { bare: 'all wrapped up', named: '{project} is all wrapped up' },
      { bare: 'nothing happening', named: 'nothing happening in {project}' },
      { bare: 'stopped and ready', named: 'stopped and ready on {project}' },
      { bare: 'free for now', named: 'free of {project} for now' },
      { bare: 'waiting on input', named: 'waiting on input for {project}' }
    ]
  }
]
