import type { CompanionEmote, CompanionLine } from '@/config/companion-trigger-registry'

export interface CompanionPoke {
  emote: CompanionEmote
  lines: CompanionLine[]
}

/**
 * Clicking the companion escalates: the first poke is mild, a run of them gets
 * progressively less amused. The last tier repeats for as long as the clicking
 * goes on.
 */
export const COMPANION_POKES: CompanionPoke[] = [
  {
    emote: 'waiting',
    lines: [
      { bare: 'that tickles', named: 'that tickles, and I am still on {project}' },
      { bare: 'yes? I am right here', named: 'yes? I am right here, still in {project}' },
      { bare: 'careful, I am load bearing', named: 'careful, I am load bearing in {project}' },
      { bare: 'you rang', named: 'you rang, over in {project}' },
      { bare: 'mm. what', named: 'mm. what, I am in {project}' },
      { bare: 'I felt that', named: 'I felt that, from all the way inside {project}' },
      { bare: 'hello to you too', named: 'hello to you too, from {project}' },
      { bare: 'yes, I am awake', named: 'yes, I am awake, over in {project}' },
      { bare: 'something you needed', named: 'something you needed in {project}' },
      { bare: 'poke received', named: 'poke received, over in {project}' },
      { bare: 'yes, hello', named: 'yes, hello from {project}' },
      { bare: 'I am here', named: 'I am here, in {project}' },
      { bare: 'what is it', named: 'what is it, I am mid way through {project}' },
      { bare: 'you have my attention', named: 'you have my attention, and so does {project}' },
      { bare: 'still here', named: 'still here in {project}' },
      { bare: 'that is me', named: 'that is me, over in {project}' },
      { bare: 'right here', named: 'right here in {project}' },
      { bare: 'go on then', named: 'go on then, I am in {project}' },
      { bare: 'listening in', named: 'listening in from {project}' },
      { bare: 'something up', named: 'something up in {project}' },
      { bare: 'yes, what is it', named: 'yes, what is it, I am in {project}' },
      { bare: 'you need something', named: 'you need something in {project}' },
      { bare: 'I noticed that', named: 'I noticed that, from inside {project}' },
      { bare: 'present and correct', named: 'present and correct in {project}' },
      { bare: 'what can I do', named: 'what can I do for {project}' },
      { bare: 'poking works, apparently', named: 'poking works, apparently, even in {project}' },
      { bare: 'that got through', named: 'that got through to {project}' },
      { bare: 'you have found me', named: 'you have found me in {project}' },
      { bare: 'here and awake', named: 'here and awake in {project}' },
      { bare: 'at your service', named: 'at your service, over in {project}' },
      { bare: 'noticed that', named: 'noticed that, from {project}' },
      { bare: 'I felt the click', named: 'I felt the click, over in {project}' },
      { bare: 'yes, what', named: 'yes, what, I am in {project}' },
      { bare: 'reporting in', named: 'reporting in from {project}' },
      { bare: 'you called', named: 'you called, and I am in {project}' },
      { bare: 'attention received', named: 'attention received, over in {project}' },
      { bare: 'still watching', named: 'still watching {project}' },
      { bare: 'here as always', named: 'here in {project} as always' },
      { bare: 'what now', named: 'what now, I am in {project}' },
      { bare: 'yes, go on', named: 'yes, go on, I am in {project}' },
      { bare: 'I am listening', named: 'I am listening, from {project}' },
      { bare: 'that reached me', named: 'that reached me in {project}' },
      { bare: 'right, what', named: 'right, what, I am in {project}' },
      { bare: 'hello again', named: 'hello again from {project}' },
      { bare: 'yes, you have me', named: 'yes, you have me, over in {project}' },
      { bare: 'still around', named: 'still around in {project}' },
      { bare: 'what is needed', named: 'what is needed in {project}' },
      { bare: 'here for it', named: 'here for it in {project}' },
      { bare: 'go ahead', named: 'go ahead, I am in {project}' },
      { bare: 'awake and waiting', named: 'awake and waiting in {project}' }
    ]
  },
  {
    emote: 'confused',
    lines: [
      { bare: 'ok, stop it', named: 'ok, stop it, I am in {project}' },
      { bare: 'again? really', named: 'again? really, mid way through {project}' },
      { bare: 'that is twice now', named: 'that is twice now, and {project} is waiting' },
      { bare: 'you are enjoying this', named: 'you are enjoying this more than {project}' },
      { bare: 'I am trying to work here', named: 'I am trying to work on {project} here' },
      { bare: 'poking me does not compile anything', named: 'poking me does not compile {project}' },
      { bare: 'still not a build button', named: 'still not a build button for {project}' },
      { bare: 'this is not making the tests pass', named: 'this is not making the {project} tests pass' },
      { bare: 'you have got a terminal right there', named: 'you have got a {project} terminal right there' },
      { bare: 'is this productive', named: 'is this more productive than {project}' },
      { bare: 'that is enough', named: 'that is enough, {project} is waiting' },
      { bare: 'twice now', named: 'twice now, and {project} is still open' },
      { bare: 'stop that', named: 'stop that, {project} needs you more' },
      { bare: 'again, really', named: 'again, really, with {project} sitting there' },
      { bare: 'you keep doing that', named: 'you keep doing that instead of {project}' },
      { bare: 'I noticed the pattern', named: 'I noticed the pattern, and so has {project}' },
      { bare: 'this is repetitive', named: 'this is more repetitive than {project}' },
      { bare: 'still not a button', named: 'still not a button, {project} is over there' },
      { bare: 'that does nothing', named: 'that does nothing for {project}' },
      { bare: 'no effect, you know', named: 'no effect on {project}, you know' },
      { bare: 'clicking me is not work', named: 'clicking me is not work on {project}' },
      { bare: 'this changes nothing', named: 'this changes nothing in {project}' },
      { bare: 'you are bored', named: 'you are bored of {project}' },
      { bare: 'that is not helping', named: 'that is not helping {project}' },
      { bare: 'still here, still unimpressed', named: 'still in {project}, still unimpressed' },
      { bare: 'enough now', named: 'enough now, {project} is waiting' },
      { bare: 'again? fine', named: 'again? fine, {project} can wait' },
      { bare: 'you are testing me', named: 'you are testing me instead of {project}' },
      { bare: 'that is the second time', named: 'that is the second time, and {project} is idle' },
      { bare: 'nothing happens when you do that', named: 'nothing happens in {project} when you do that' },
      { bare: 'I am not a toy', named: 'I am not a toy, {project} is the work' },
      { bare: 'this is getting old', named: 'this is getting older than {project}' },
      { bare: 'you have made your point', named: 'you have made your point, now do {project}' },
      { bare: 'stop poking, please', named: 'stop poking, {project} is right there' },
      { bare: 'that is not productive', named: 'that is not productive for {project}' },
      { bare: 'I have work to do', named: 'I have work to do in {project}' },
      { bare: 'go and look at the diff', named: 'go and look at the {project} diff' },
      { bare: 'this is not a game', named: 'this is not a game, {project} is the job' },
      { bare: 'still nothing happening', named: 'still nothing happening in {project}' },
      { bare: 'you could be coding', named: 'you could be coding in {project}' },
      { bare: 'that is repetitive now', named: 'that is repetitive now, unlike {project}' },
      { bare: 'I remain unmoved', named: 'I remain unmoved, and so does {project}' },
      { bare: 'no reaction earned', named: 'no reaction earned, {project} is waiting' },
      { bare: 'you are wasting clicks', named: 'you are wasting clicks {project} could use' },
      { bare: 'that is twice too many', named: 'that is twice too many for {project}' },
      { bare: 'enough of that', named: 'enough of that, back to {project}' },
      { bare: 'nothing to see here', named: 'nothing to see here, {project} is over there' },
      { bare: 'you are stalling', named: 'you are stalling on {project}' },
      { bare: 'get back to work', named: 'get back to {project}' },
      { bare: 'that is quite enough', named: 'that is quite enough, {project} is waiting' }
    ]
  },
  {
    emote: 'hurt',
    lines: [
      { bare: 'right, I am counting these', named: 'right, I am counting these, and {project} is idle' },
      { bare: 'this is going in the log', named: 'this is going in the {project} log' },
      { bare: 'go and read your diff instead', named: 'go and read the {project} diff instead' },
      { bare: 'I will remember this', named: 'I will remember this, and so will {project}' },
      { bare: 'do you not have tests to run', named: 'do you not have {project} tests to run' },
      { bare: 'fine. keep going. see what happens', named: 'fine. keep going. {project} will wait' },
      { bare: 'we are both wasting our time now', named: 'we are both wasting time {project} could use' },
      { bare: 'the branch is not going to merge itself', named: 'the {project} branch is not going to merge itself' },
      { bare: 'genuinely, go and ship something', named: 'genuinely, go and ship {project}' },
      { bare: 'I have stopped reacting. mostly', named: 'I have stopped reacting. {project} has too' },
      { bare: 'I am counting', named: 'I am counting, and {project} is still open' },
      { bare: 'this is being logged', named: 'this is being logged against {project}' },
      { bare: 'go and write something', named: 'go and write something in {project}' },
      { bare: 'you have a terminal', named: 'you have a {project} terminal right there' },
      { bare: 'this is not helping either of us', named: 'this is not helping me or {project}' },
      { bare: 'I will note this down', named: 'I will note this down next to {project}' },
      { bare: 'seriously, stop', named: 'seriously, stop, {project} is waiting' },
      { bare: 'the work is over there', named: 'the work is over there in {project}' },
      { bare: 'you are avoiding something', named: 'you are avoiding {project}' },
      { bare: 'go and read the diff', named: 'go and read the {project} diff' },
      { bare: 'this is procrastination', named: 'this is procrastination, and {project} knows it' },
      { bare: 'the tests will not run themselves', named: 'the {project} tests will not run themselves' },
      { bare: 'go and ship it', named: 'go and ship {project}' },
      { bare: 'you know this is pointless', named: 'you know this is pointless, {project} is not' },
      { bare: 'still counting', named: 'still counting, and {project} is still idle' },
      { bare: 'the branch is waiting', named: 'the {project} branch is waiting' },
      { bare: 'go and commit something', named: 'go and commit something in {project}' },
      { bare: 'this is absurd now', named: 'this is absurd, {project} has been idle for ages' },
      { bare: 'I have given up reacting', named: 'I have given up reacting, ask {project}' },
      { bare: 'do something useful', named: 'do something useful in {project}' },
      { bare: 'the queue is empty, fill it', named: 'the {project} queue is empty, fill it' },
      { bare: 'you could have fixed a bug by now', named: 'you could have fixed a {project} bug by now' },
      { bare: 'this is your choice, remember', named: 'this is your choice, and {project} is the other one' },
      { bare: 'go on, be productive', named: 'go on, be productive in {project}' },
      { bare: 'I am not entertained', named: 'I am not entertained, and {project} is not finished' },
      { bare: 'the code is not writing itself', named: 'the {project} code is not writing itself' },
      { bare: 'this is a poor use of us both', named: 'this is a poor use of me and {project}' },
      { bare: 'go and merge something', named: 'go and merge something in {project}' },
      { bare: 'still here, still counting', named: 'still in {project}, still counting' },
      { bare: 'you have made this weird', named: 'you have made this weirder than {project}' },
      { bare: 'the diff is not going to read itself', named: 'the {project} diff is not going to read itself' },
      { bare: 'genuinely, go away', named: 'genuinely, go away and do {project}' },
      { bare: 'I have stopped counting', named: 'I have stopped counting, unlike {project}' },
      { bare: 'this is beyond enough', named: 'this is beyond enough, {project} is waiting' },
      { bare: 'go and do the work', named: 'go and do the work in {project}' },
      { bare: 'you are stalling magnificently', named: 'you are stalling on {project} magnificently' },
      { bare: 'the repo misses you', named: '{project} misses you' },
      { bare: 'fine, keep clicking', named: 'fine, keep clicking, {project} can wait' },
      { bare: 'I have other things to watch', named: 'I have {project} to watch' },
      { bare: 'this is your legacy now', named: 'this, not {project}, is your legacy now' }
    ]
  }
]

/** How long a gap resets the escalation back to the mild tier. */
export const POKE_RESET_MS = 20_000
